/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pb_msg.proto */

#ifndef PROTOBUF_C_pb_5fmsg_2eproto__INCLUDED
#define PROTOBUF_C_pb_5fmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Pb__Msg Pb__Msg;


/* --- enums --- */


/* --- messages --- */

struct  _Pb__Msg
{
  ProtobufCMessage base;
  uint32_t msg_id;
  uint32_t cmd_id;
  protobuf_c_boolean has_err_id;
  uint32_t err_id;
  char *string;
  protobuf_c_boolean has_number;
  float number;
};
#define PB__MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb__msg__descriptor) \
    , 0, 0, 0, 0, NULL, 0, 0 }


/* Pb__Msg methods */
void   pb__msg__init
                     (Pb__Msg         *message);
size_t pb__msg__get_packed_size
                     (const Pb__Msg   *message);
size_t pb__msg__pack
                     (const Pb__Msg   *message,
                      uint8_t             *out);
size_t pb__msg__pack_to_buffer
                     (const Pb__Msg   *message,
                      ProtobufCBuffer     *buffer);
Pb__Msg *
       pb__msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb__msg__free_unpacked
                     (Pb__Msg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Pb__Msg_Closure)
                 (const Pb__Msg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pb__msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pb_5fmsg_2eproto__INCLUDED */
